### ISSUE TITLE
play speed

### ISSUE THREAD

**Issue by kevinlin505** [StreetVoice/HysteriaPlayer#106]
Great library.
The one question I have is does this library support play speed control? like 1.5x, 2x the normal speed?
If not, do you have any plan on integrating it?

**Comment by saiday** [comment]
@kevinlin505 
Since HysteriaPlayer is sitting on top of AVPlayer, so change play speed is a easy task, all we need to do is set `rate` property. (0.50, 0.67, 0.80, 1.0, 1.25, 1.50, and 2.0)
Also, rate functionality provided by AVPlayer is pitch optimized.

Answer to your question, I don't think HysteriaPlayer should support play speed rate setting. The main purpose of HysteriaPlayer is handling playback functionality.
