### ISSUE TITLE
getHysteriaPlayerStatus returns wrong status while buffering

### ISSUE THREAD

**Issue by icenodescode** [StreetVoice/HysteriaPlayer#125]
getHysteriaPlayerStatus returns HysteriaPlayerStatusUnknown while buffering

**Comment by saiday** [comment]
@icenodescode yes, this could happen. Since playback is paused by AVFoundation at the very first time.
Ideally the status would become `HysteriaPlayerStatusBuffering` when you loaded the next buffer.

The status transition graph is like:
Playing -> (out of buffers) -> `HysteriaPlayerStatusUnknown` -> (buffer loaded) -> `HysteriaPlayerStatusBuffering`

Please reopen this issue if `HysteriaPlayerStatusUnknown` not behaves like description.
